import "@/style/globals.css";
import style from "./layout.module.css";
import { Header, Nav, Body } from "@/components/layouts";

export const metadata = {
  title: "dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={style.body}>
        <Nav />
        <Body>
          {/* <Header /> */}
          {children}
        </Body>
      </body>
    </html>
  );
}
